utils: missing format! in context macro
The formatting directives are shown to the user:

```
Error: unknown flag: --user root:root
See 'podman run --help'
ERROR running reinstall command: Failed to run command: {self:#?}
```

This is due to a lack of `format!` directive

Signed-off-by: Omer Tuchfeld <omer@tuchfeld.dev>