container: Force on anonymous fetches if no config file
We've seen a weird error out of the container stack when
we're not authorized to fetch an image, *and* no pull secret
is set up.

e.g.  https://github.com/coreos/fedora-coreos-tracker/issues/1328#issuecomment-1292067775

```
error: remote error: getting username and password: 1 error occurred:
	* reading JSON file "/run/containers/62011/auth.json": open /run/containers/62011/auth.json: permission denied
```

We don't want the containers/image stack trying to read the "standard"
config paths at the moment for a few reasons; one is that the standard
paths conflate "root" and "the system".  We want to support
separate pull secrets.  But, it should also work to symlink
the authfile.