install: Fix exec helper to not swallow unexpected args
Our `exec-in-host-mount-namespace` internal helper was intended
to be a "passthrough" that accepts whatever child arguments.

However I misunderstood how to do this in clap.  Before this
change we get:

```
$ bootc blabla
ERROR Re-exec in host mountns: Missing command
```

i.e. the exec code kicks in because `external_subcommand` takes
over *everything* unknown.

Fix things to use `trailing_var_arg` which is intended for this case.

After this patch:

```
$ bootc blabla
error: unrecognized subcommand 'blabla'

Usage: bootc <COMMAND>

For more information, try '--help'.
```

Signed-off-by: Colin Walters <walters@verbum.org>